-- 16. stories (10)
INSERT INTO stories ("Id", "Title", "Description", "Content", "CoverImageUrl", "Genre", "MoralLesson", "Language", "AgeBand", "Status", "Source", "IsPublished", "ChildVisibleAt", "ArchivedReason", "AuthorUserId", "ChildProfileId", "CreatedAt", "IsDeleted")
VALUES
    (1, 'Chu Tho Thong Minh', 'Cau chuyen ve chu tho biet dung tri thong minh de thoat hiem', 'Ngay xua, co mot chu tho rat thong minh song trong khu rung...', 'https://example.com/covers/story1.png', 'Ngu ngon', 'Su thong minh giup vuot qua kho khan', 'vi', 'Age_6_8', 'Ready', 'Manual', true, NOW() - INTERVAL '30 days' + INTERVAL '2 hours', NULL, 2, 1, NOW() - INTERVAL '30 days', false),
    (2, 'Rung Xanh Ky Dieu', 'Hanh trinh kham pha khu rung day mau sac', 'Trong khu rung xanh co rat nhieu dieu ky dieu dang cho duoc kham pha...', 'https://example.com/covers/story2.png', 'Phieu luu', 'Tran trong thien nhien', 'vi', 'Age_9_12', 'Draft', 'Ai', false, NULL, NULL, 7, 2, NOW() - INTERVAL '28 days', false),
    (3, 'Vuong Quoc Co Tich', 'Mot vuong quoc noi phep thuat va long tot ngu tri', 'Ngay xua o mot vuong quoc xa xoi...', 'https://example.com/covers/story3.png', 'Co tich', 'Long tot se duoc den dap', 'vi', 'Age_6_8', 'Ready', 'Manual', true, NOW() - INTERVAL '26 days' + INTERVAL '2 hours', NULL, 3, 3, NOW() - INTERVAL '26 days', false),
    (4, 'Hanh Trinh Vu Tru', 'Chuyen phieu luu cua mot nha du hanh nho tuoi', 'Mot ngay no, ban nho quyet dinh du hanh len vu tru...', 'https://example.com/covers/story4.png', 'Khoa hoc vien tuong', 'Kham pha va hoc hoi khong ngung', 'vi', 'Age_9_12', 'ContentReview', 'Ai', false, NULL, NULL, 8, 4, NOW() - INTERVAL '24 days', false),
    (5, 'Nguoi Ban Tot', 'Cau chuyen ve tinh ban chan thanh giua hai dua tre', 'Hai nguoi ban than thiet cung nhau vuot qua kho khan...', 'https://example.com/covers/story5.png', 'Doi thuong', 'Tinh ban chan thanh la vo gia', 'vi', 'Age_6_8', 'Approved', 'Manual', false, NOW() - INTERVAL '22 days' + INTERVAL '2 hours', NULL, 4, 5, NOW() - INTERVAL '22 days', false),
    (6, 'Bi Mat Dai Duong', 'Kham pha the gioi ky dieu duoi day dai duong', 'Sau lop song bien xanh la ca mot the gioi ky dieu...', 'https://example.com/covers/story6.png', 'Phieu luu', 'Bao ve moi truong bien', 'vi', 'Age_9_12', 'Ready', 'Ai', true, NOW() - INTERVAL '20 days' + INTERVAL '2 hours', NULL, 9, 6, NOW() - INTERVAL '20 days', false),
    (7, 'Gia Dinh Hanh Phuc', 'Nhung khoanh khac am ap trong mot gia dinh nho', 'Moi buoi toi, ca gia dinh quay quan ben nhau...', 'https://example.com/covers/story7.png', 'Doi thuong', 'Yeu thuong gia dinh', 'vi', 'Age_6_8', 'Draft', 'Manual', false, NULL, NULL, 5, 7, NOW() - INTERVAL '19 days', false),
    (8, 'Sieu Nhan Ti Hon', 'Cau be co suc manh dac biet bao ve xom lang', 'Trong mot ngoi lang nho, co mot cau be so huu suc manh dac biet...', 'https://example.com/covers/story8.png', 'Sieu anh hung', 'Dung cam bao ve nguoi yeu the', 'vi', 'Age_9_12', 'OutlineReview', 'Ai', false, NULL, NULL, 10, 8, NOW() - INTERVAL '17 days', false),
    (9, 'Chuyen Phieu Luu Rung Ram', 'Nhom ban cung nhau kham pha khu rung bi an', 'Bon nguoi ban quyet dinh kham pha khu rung phia sau lang...', 'https://example.com/covers/story9.png', 'Phieu luu', 'Doan ket tao nen suc manh', 'vi', 'Age_6_8', 'Rejected', 'Manual', false, NULL, NULL, 6, 9, NOW() - INTERVAL '15 days', false),
    (10, 'Tran Bong Da Dang Nho', 'Bai hoc ve tinh than the thao va fair-play', 'Tran chung ket bong da cua truong dien ra day kich tinh...', 'https://example.com/covers/story10.png', 'The thao', 'Tinh than fair-play trong the thao', 'vi', 'Age_9_12', 'Ready', 'Ai', true, NOW() - INTERVAL '13 days' + INTERVAL '2 hours', NULL, 7, 10, NOW() - INTERVAL '13 days', false)
ON CONFLICT ("Id") DO NOTHING;
