-- 21. story_versions (10)
INSERT INTO story_versions ("Id", "StoryId", "VersionNo", "Title", "Content", "OutlineOpening", "OutlineDevelopment", "OutlineEnding", "Lesson", "ReadabilityFkgl", "ReadabilityFre", "SafetyScore", "EditType", "EditorUserId", "OutlineApprovedByUserId", "OutlineApprovedAt", "IsCurrent", "CreatedAt", "IsDeleted")
VALUES
    (1, 1, 1, 'Chu Tho Thong Minh - Ban 1', 'Ngay xua, co mot chu tho rat thong minh song trong khu rung...', 'Gioi thieu chu tho va khu rung', 'Chu tho gap nguy hiem va tim cach thoat', 'Chu tho thoat hiem nho su thong minh', 'Su thong minh giup vuot qua kho khan', 3.200, 78.500, 95.000, 'Initial', 2, 2, NOW() - INTERVAL '30 days' + INTERVAL '1 hour', true, NOW() - INTERVAL '30 days', false),
    (2, 2, 1, 'Rung Xanh Ky Dieu - Ban 1', 'Trong khu rung xanh co rat nhieu dieu ky dieu dang cho duoc kham pha...', 'Gioi thieu khu rung', 'Hanh trinh kham pha', 'Bai hoc ve thien nhien', 'Tran trong thien nhien', 4.100, 72.300, 90.000, 'Initial', NULL, NULL, NULL, true, NOW() - INTERVAL '28 days', false),
    (3, 3, 1, 'Vuong Quoc Co Tich - Ban 1', 'Ngay xua o mot vuong quoc xa xoi...', 'Gioi thieu vuong quoc', 'Thu thach cua nhan vat chinh', 'Long tot chien thang', 'Long tot se duoc den dap', 2.800, 82.000, 97.000, 'Initial', 3, 3, NOW() - INTERVAL '26 days' + INTERVAL '1 hour', true, NOW() - INTERVAL '26 days', false),
    (4, 4, 1, 'Hanh Trinh Vu Tru - Ban 1', 'Mot ngay no, ban nho quyet dinh du hanh len vu tru...', 'Gioi thieu chuyen du hanh', 'Kham pha cac hanh tinh', 'Tro ve trai dat voi nhieu bai hoc', 'Kham pha va hoc hoi khong ngung', 4.500, 68.000, 88.000, 'Initial', 8, 3, NOW() - INTERVAL '24 days' + INTERVAL '1 hour', true, NOW() - INTERVAL '24 days', false),
    (5, 5, 1, 'Nguoi Ban Tot - Ban 1', 'Hai nguoi ban than thiet cung nhau vuot qua kho khan...', 'Gioi thieu hai nguoi ban', 'Kho khan thu thach tinh ban', 'Tinh ban duoc cung co', 'Tinh ban chan thanh la vo gia', 3.000, 80.000, 96.000, 'Initial', NULL, 4, NOW() - INTERVAL '22 days' + INTERVAL '1 hour', true, NOW() - INTERVAL '22 days', false),
    (6, 6, 1, 'Bi Mat Dai Duong - Ban 1', 'Sau lop song bien xanh la ca mot the gioi ky dieu...', 'Gioi thieu the gioi dai duong', 'Kham pha bi mat duoi day bien', 'Bai hoc bao ve moi truong', 'Bao ve moi truong bien', 3.900, 74.000, 92.000, 'Initial', 9, 4, NOW() - INTERVAL '20 days' + INTERVAL '1 hour', true, NOW() - INTERVAL '20 days', false),
    (7, 7, 1, 'Gia Dinh Hanh Phuc - Ban 1', 'Moi buoi toi, ca gia dinh quay quan ben nhau...', 'Gioi thieu gia dinh', 'Nhung khoanh khac dang nho', 'Tran trong gia dinh', 'Yeu thuong gia dinh', 2.500, 85.000, 98.000, 'Initial', NULL, NULL, NULL, true, NOW() - INTERVAL '19 days', false),
    (8, 8, 1, 'Sieu Nhan Ti Hon - Ban 1', 'Trong mot ngoi lang nho, co mot cau be so huu suc manh dac biet...', 'Gioi thieu sieu nhan ti hon', 'Cuoc chien bao ve xom lang', 'Chien thang cai xau', 'Dung cam bao ve nguoi yeu the', 4.200, 70.000, 89.000, 'Initial', 10, NULL, NULL, true, NOW() - INTERVAL '17 days', false),
    (9, 9, 1, 'Chuyen Phieu Luu Rung Ram - Ban 1', 'Bon nguoi ban quyet dinh kham pha khu rung phia sau lang...', 'Gioi thieu nhom ban', 'Thu thach trong rung ram', 'Doan ket vuot kho khan', 'Doan ket tao nen suc manh', 3.600, 76.000, 91.000, 'Initial', NULL, 6, NOW() - INTERVAL '15 days' + INTERVAL '1 hour', false, NOW() - INTERVAL '15 days', false),
    (10, 10, 1, 'Tran Bong Da Dang Nho - Ban 1', 'Tran chung ket bong da cua truong dien ra day kich tinh...', 'Gioi thieu tran dau', 'Dien bien gay can', 'Bai hoc ve fair-play', 'Tinh than fair-play trong the thao', 4.000, 73.000, 94.000, 'Initial', 7, 6, NOW() - INTERVAL '13 days' + INTERVAL '1 hour', true, NOW() - INTERVAL '13 days', false)
ON CONFLICT ("Id") DO NOTHING;
